-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 21:30:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema incrivel
-- -----------------------------------------------------
-- Arraiá IN-CRI-VÉL
-- Professor Wanderson Santos
-- professor@wandersonsantos.com

-- -----------------------------------------------------
-- Schema incrivel
--
-- Arraiá IN-CRI-VÉL
-- Professor Wanderson Santos
-- professor@wandersonsantos.com
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `incrivel` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `incrivel` ;

-- -----------------------------------------------------
-- Table `incrivel`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome_pessoa` VARCHAR(45) NOT NULL,
  `cpf_pessoa` CHAR(11) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `tipo_pessoa` SMALLINT(1) NOT NULL COMMENT '1-Funcionario; 2-Cliente',
  `bol_ativo` SMALLINT(1) NOT NULL DEFAULT 1 COMMENT '0-Inativo\n1-Ativo',
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(45) NOT NULL,
  `desc_grupo` TEXT NOT NULL,
  `tipo_grupo` SMALLINT NOT NULL COMMENT '1-Tereceiro\n2-Funcionario\n3-Convidado',
  `bol_ativo` SMALLINT NOT NULL DEFAULT 1 COMMENT '0-Inativo\n1-Ativo',
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `desc_evento` VARCHAR(45) NOT NULL,
  `data_evento` DATE NOT NULL,
  `link_credenciamento` VARCHAR(100) NOT NULL,
  `link_documentos` VARCHAR(100) NULL,
  `valor_ingresso` DECIMAL(10,2) NOT NULL,
  `local_evento` TEXT NOT NULL,
  `pessoa_idPessoa_resp_pgto` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Pessoa_idx` (`pessoa_idPessoa_resp_pgto` ASC) ,
  CONSTRAINT `fk_Evento_Pessoa`
    FOREIGN KEY (`pessoa_idPessoa_resp_pgto`)
    REFERENCES `incrivel`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`TipoBarraca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`TipoBarraca` (
  `idTipoBarraca` INT NOT NULL AUTO_INCREMENT,
  `desc_tipo_barraca` VARCHAR(45) NOT NULL,
  `bol_ativo` SMALLINT NOT NULL,
  PRIMARY KEY (`idTipoBarraca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Barraca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Barraca` (
  `idBarraca` INT NOT NULL AUTO_INCREMENT,
  `desc_barraca` VARCHAR(45) NOT NULL,
  `area_evento` VARCHAR(45) NOT NULL,
  `site` VARCHAR(100) NULL,
  `rede_social` VARCHAR(45) NULL,
  `telefone` CHAR(11) NOT NULL,
  `cpf_cnpj` CHAR(14) NOT NULL,
  `bol_ativo` SMALLINT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  `TipoBarraca_idTipoBarraca` INT NOT NULL,
  PRIMARY KEY (`idBarraca`),
  INDEX `fk_Barraca_Evento1_idx` (`Evento_idEvento` ASC) ,
  INDEX `fk_Barraca_TipoBarraca1_idx` (`TipoBarraca_idTipoBarraca` ASC) ,
  CONSTRAINT `fk_Barraca_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `incrivel`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Barraca_TipoBarraca1`
    FOREIGN KEY (`TipoBarraca_idTipoBarraca`)
    REFERENCES `incrivel`.`TipoBarraca` (`idTipoBarraca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `desc_produto` VARCHAR(45) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `bol_ativo` SMALLINT NOT NULL DEFAULT 1 COMMENT '0-Inativo\n1-Ativo',
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`produto_barraca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`produto_barraca` (
  `Produto_idProduto` INT NOT NULL,
  `Barraca_idBarraca` INT NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Barraca_idBarraca`),
  INDEX `fk_Produto_has_Barraca_Barraca1_idx` (`Barraca_idBarraca` ASC) ,
  INDEX `fk_Produto_has_Barraca_Produto1_idx` (`Produto_idProduto` ASC) ,
  CONSTRAINT `fk_Produto_has_Barraca_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `incrivel`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Barraca_Barraca1`
    FOREIGN KEY (`Barraca_idBarraca`)
    REFERENCES `incrivel`.`Barraca` (`idBarraca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `data_registro` TIMESTAMP NOT NULL,
  `bol_ativo` SMALLINT NOT NULL DEFAULT 1 COMMENT '0-Inativo\n1-Ativo',
  `Pessoa_idPessoa` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_idPessoa` ASC) ,
  INDEX `fk_Funcionario_Evento1_idx` (`Evento_idEvento` ASC) ,
  INDEX `fk_Funcionario_Grupo1_idx` (`Grupo_idGrupo` ASC) ,
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `incrivel`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `incrivel`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `incrivel`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Atracao` (
  `idAtracao` INT NOT NULL,
  `titulo_atracao` VARCHAR(45) NOT NULL,
  `desc_atracao` TEXT NOT NULL,
  `data_hora_apresentacao` TIMESTAMP NOT NULL,
  `bol_ativo` SMALLINT NOT NULL DEFAULT 1 COMMENT '0-Inativo\n1-Ativo',
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idAtracao`),
  INDEX `fk_Atracao_Evento1_idx` (`Evento_idEvento` ASC) ,
  CONSTRAINT `fk_Atracao_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `incrivel`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Documentos` (
  `idDocumentos` INT NOT NULL,
  `titulo_documento` VARCHAR(45) NOT NULL,
  `desc_documento` TEXT NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `link_publico` VARCHAR(100) NULL,
  `doc_publico` SMALLINT NOT NULL DEFAULT 0 COMMENT '0-Não\n1-Sim',
  `bol_ativo` SMALLINT NOT NULL DEFAULT 0 COMMENT '0-Inativo\n1-Ativo',
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idDocumentos`),
  INDEX `fk_Documentos_Evento1_idx` (`Evento_idEvento` ASC) ,
  CONSTRAINT `fk_Documentos_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `incrivel`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`AreaEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`AreaEvento` (
  `idAreaEvento` INT NOT NULL,
  `desc_area_evento` VARCHAR(45) NOT NULL,
  `bol_ativo` SMALLINT NOT NULL DEFAULT 1 COMMENT '0-Inativo\n1-Ativo',
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idAreaEvento`),
  INDEX `fk_AreaEvento_Evento1_idx` (`Evento_idEvento` ASC) ,
  CONSTRAINT `fk_AreaEvento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `incrivel`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`TipoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`TipoServico` (
  `idTipoServico` INT NOT NULL AUTO_INCREMENT COMMENT 'Alimento/Bebida/Lazer/Sergurança/Limpeza',
  `desc_tipo_servico` VARCHAR(45) NOT NULL,
  `bol_ativo` SMALLINT NOT NULL,
  PRIMARY KEY (`idTipoServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`TipoParceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`TipoParceiro` (
  `idTipoParceiro` INT NOT NULL AUTO_INCREMENT,
  `desc_tipo_parceiro` VARCHAR(45) NOT NULL,
  `bol_ativo` SMALLINT NOT NULL,
  PRIMARY KEY (`idTipoParceiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Parceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Parceiro` (
  `idParceiro` INT NOT NULL AUTO_INCREMENT,
  `nome_parceiro` VARCHAR(45) NOT NULL,
  `desc_parceiro` TEXT NULL,
  `bol_ativo` SMALLINT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  `TipoServico_idTipoServico` INT NOT NULL,
  `TipoParceiro_idTipoParceiro` INT NOT NULL,
  PRIMARY KEY (`idParceiro`),
  INDEX `fk_Parceiro_Evento1_idx` (`Evento_idEvento` ASC) ,
  INDEX `fk_Parceiro_TipoServico1_idx` (`TipoServico_idTipoServico` ASC) ,
  INDEX `fk_Parceiro_TipoParceiro1_idx` (`TipoParceiro_idTipoParceiro` ASC) ,
  CONSTRAINT `fk_Parceiro_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `incrivel`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parceiro_TipoServico1`
    FOREIGN KEY (`TipoServico_idTipoServico`)
    REFERENCES `incrivel`.`TipoServico` (`idTipoServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parceiro_TipoParceiro1`
    FOREIGN KEY (`TipoParceiro_idTipoParceiro`)
    REFERENCES `incrivel`.`TipoParceiro` (`idTipoParceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Grupo_Acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Grupo_Acesso` (
  `Grupo_idGrupo` INT NOT NULL,
  `AreaEvento_idAreaEvento` INT NOT NULL,
  `permitido` SMALLINT NOT NULL COMMENT '0-Não\n1-Sim',
  PRIMARY KEY (`Grupo_idGrupo`, `AreaEvento_idAreaEvento`),
  INDEX `fk_Grupo_has_AreaEvento_AreaEvento1_idx` (`AreaEvento_idAreaEvento` ASC) ,
  INDEX `fk_Grupo_has_AreaEvento_Grupo1_idx` (`Grupo_idGrupo` ASC) ,
  CONSTRAINT `fk_Grupo_has_AreaEvento_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `incrivel`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_AreaEvento_AreaEvento1`
    FOREIGN KEY (`AreaEvento_idAreaEvento`)
    REFERENCES `incrivel`.`AreaEvento` (`idAreaEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incrivel`.`Ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incrivel`.`Ficha` (
  `Produto_idProduto` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `forma_pgto` SMALLINT NOT NULL COMMENT '1-Dinheiro\n2-Crédito\n3-Débito\n4-PIX',
  `valor_ficha` DECIMAL(10,2) NOT NULL,
  `data_validade` TIMESTAMP NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pessoa_idPessoa`),
  INDEX `fk_Produto_has_Pessoa_Pessoa1_idx` (`Pessoa_idPessoa` ASC) ,
  INDEX `fk_Produto_has_Pessoa_Produto1_idx` (`Produto_idProduto` ASC) ,
  CONSTRAINT `fk_Produto_has_Pessoa_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `incrivel`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `incrivel`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
